name: Generate Composite Image Daily

permissions:
  contents: write

on:
  schedule:
    - cron: "0 16 * * *" # 每天 UTC 16 点执行一次（北京时间 0:00）
  workflow_dispatch: # 可手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      BG_URL: ${{ secrets.BG_URL }}

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt

      - name: 🖼 Run main script
        run: python main.py

      # 自动添加和提交更改
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "." # 添加所有更改
          message: "Automated changes by GitHub Actions" # 提交信息
          author_name: github-actions[bot] # 以 GitHub Actions bot 身份提交，而非仓库 owner
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的默认 token
